### ISSUE TITLE
Using selector in the browser

### ISSUE THREAD

**Issue by jotaelesalinas** [gizt/selector#50]
Hi! Thank you for this package.

I was wondering how I can use it a web browser.

I would like to build an interactive application in which the user enters the query string and the data is highlighted/extracted in real time.

**Comment by rezigned** [comment]
@jotaelesalinas Hi, I would suggest to use bundle tools like parcel, webpack, etc. The other options could be some module loader like `requirejs` in browser. For example:

```html
<script src="https://requirejs.org/docs/release/2.3.6/comments/require.js"></script>
<script src="https://unpkg.com/@gizt/selector@1.0.9/dist/single/index.js"></script>

<script>
require(["selector"], (s) => {
  console.log(s.default("a", {"a": 10})) // print 10
})
</script>
```

**Comment by jotaelesalinas** [comment]
Ok, thanks a lot!
